id: P2527D757
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA0XLD1FCC1009B83
  instance_id: http://purl.bdrc.io/resource/IE1KG4230
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - བདེ་མཆོག་ནམ་མཁའ་དང་མཉམ་པའི་རྒྱུད་ཀྱི་རྩ་འགྲེལ།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P127
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    ed4d751674cb43f6b263f117a76da0cb:
      title: པོད ༡་བདེ་མཆོག་ནམ་མཁའ་དང་མཉམ་པའི་རྒྱུད་ཀྱི་རྩ་འགྲེལ
      volume_number: 1
      base_file: UT1KG4230_I1PD97692_0000.txt
      reference: http://purl.bdrc.io/resource/VLE80D49E93D5A6A8B
      image_group: I1PD97692
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW1KG4230
  - http://purl.bdrc.io/resource/W1KG4230
  ocr_software: Namsel
created_at: '2021-12-22T10:39:17.726724'
last_modified_at: '2021-12-22T10:39:17.726730'
